config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   resources :users do
    member do
      get 'index_attendance', to: 'users#index_attendance'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit_overwork_approval'
      patch 'update_overwork_approval'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' 
      get 'attendances/attendance_log'
      get 'attendances/edit_overtime_request'
      patch 'attendances/update_overtime_request'
    end
     collection {post :import} 
     member do
     end 
     resources :bases 
      resources :attendances 
    
      resources :month_approvals
   end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bases, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :approvalas, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
 
 
 def User.digest(string)
  cost = 
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
   BCrypt::Password.create(string, cost: cost)
 end

 def User.new_token
  SecureRandom.urlsafe_base64
 end
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    CSV.foreach(file.path, encoding: "CP932:UTF-8", headers: true) do |row|
      user = find_by(id: row["id"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
  end
  
  def self.updatable_attributes
    ['name', 'email', 'affiliation', 'employee_number', 'card_id', 'basic_time', 'work_start_time', 'work_end_time', 'superior', 'admin','password' ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_overwork_approval, :update_overwork_approval]
  before_action :logged_in_user, only: [:index, :show, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_overwork_approval, :update_overwork_approval]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_one_month, only: [:show, :edit_one_month, :edit_overwork_approval, :update_overwork_approval]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info, :edit_overwork_approval, :update_overwork_approval]
  

  def index
    @users = User.all
    if params[:name].present?
      @users = @users.get_by_name params[:name] 
    end
  end
  
  def index_attendance
    @users = User.all.includes(:attendances)
  end
  
  def import
    # fileはtmpに自動で一時保存される
    User.import(params[:file])
    redirect_to users_path
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def edit_overwork_approval
     @users = User.find(params[:id])
  end
  
  def update_overwork_approval
     @users = User.find(params[:id])
  end
  
  def update_basic_info
  
    if User.update(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to  users_url
      
    else
      flash[:danger] = "更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to edit_basic_info_user_url
    end
  end  
  # paramsハッシュからユーザーを取得します。
    
  def set_user
      @user = User.find(params[:id])
  end

    # ログイン済みのユーザーか確認します。
  def logged_in_user
    unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
    end
  end

    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
  def correct_user
      redirect_to(root_url) unless current_user?(@user)
  end

    # システム管理権限所有かどうか判定します。
  def admin_user
      redirect_to root_url unless current_user.admin?
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :employee_number, :uid, :basic_time, :work_start_time, :work_end_time, :superior, :admin, :password)
    end
 
  def basic_info_params
      params.require(:user).permit(:basic_time, :work_start_time, :work_end_time)
  end

  def overwork_approval_params
    params.require(:user).permit(:over_work_in, :overwork_end, :superior_affiliation)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
   # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_start_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_start_time, class: "form-control" %>
            
            <%= f.label :work_end_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_end_time, class: "form-control" %>


            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>






                 

app/views/users/_edit_overwork_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
       <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
       <div class="col-md-10 col-md-offset-1">
      
            <%= form_with(model: @user, url: update_overwork_approval_user_path(@user), local: true, method: :patch) do |f| %>
             
               
               <table class = "table table-bordered table-condensed table-striped  table-overwork_approval">
        　　       <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>翌日</th>
                    <th>業務処理内容</th>
                    <th>指示者確認
                      <div class = "maru size_small black">
                        <div class = "letter3">印</div>
                      </div>
                    </th>
                  </tr>
                 </thead>
               <tbody> 
                 <%= f.hidden_field :id, :value => @attendance %>
                  <tr>
                    <td><%= select_date(session[:currentdate],:use_month_numbers => true) %></td>
                    <td><%= "#" %></td>
                    <td><%= f.time_field :overwork_end, class: "form-control" %></td>
                    <td><%= f.check_box(:next_day, { :checked => false  }) %></td>
                    <td><%= f.text_field :overwork_memo, class: "form-control" %></td>
                    <td><%= f.select :superior, [["superior", "superior"],["管理者", "管理者"],["上長A", "上長A"],["上長B", "上長B"]],:include_blank => true ,class:"form-control" %></td>
                  </tr>
               
               </tbody>
            </table>
              <div type = margin-top: 10px></div> 
               <div class = center>
                 <%= link_to "変更を送信する", "#",class: "btn btn-primary btn-overwork-approval" %>
                 <button type="button" class="btn btn-default btn-opverwork-approval" data-dismiss="modal">
                   キャンセル
                 </button>
               </div>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email, class: "label-#{yield(:class_text)}" %>
    <%= f.email_field :email, class: "form-control" %>
  
    <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :affiliation, class: "form-control" %>
  
    <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :employee_number, class: "form-control" %>
  
    <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :uid, class: "form-control" %>
  
    <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :basic_time, class: "form-control" %>
  
    <%= f.label :work_start_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :work_start_time, class: "form-control" %>
  
    <%= f.label :work_end_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :work_end_time, class: "form-control" %>
    
    <%= f.label :superior, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :superior, class: "form-control" %>
    
    <%= f.label :admin, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :admin, class: "form-control" %>
    
    <%= f.label :password, class: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password, class: "form-control" %>
    
    <div style = "margin-top: 10px">
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-user_edit" %>
    </div>
   <% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
       <p><%= @user.name %></p>
     <li><%= link_to "削除", @user, method: :delete, class: "btn btn-primary" %></li>
       
       <div style = "margin-top: 10px"></div>
     <li><%= link_to "編集", edit_user_path, class: "btn btn-lg btn-primary" %></li>
       <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/edit_overwork_approval.js.erb
$("#edit-overwork-approval").html("<%= escape_javascript(render 'edit_overwork_approval') %>");
$("#edit-overwork-approval").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

 <div class="col-md-6 col-md-offset-1">
<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <div style = "margin-top:10px" ></div>
  <%= submit_tag "インポート", class: "btn btn-block btn-primary" %>
<% end %>
 </div>
 　  
 <div class="col-md-6 col-md-offset-1">
    <% @users.each do |user| %>
          <li><%= link_to user.name, user %></li>
           
            <div style = "margin-top: 10px"></div>
          <li><%= link_to "削除", user, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %></li>
       
          <div style = "margin-top: 10px"></div>
          <li><%= link_to "編集", edit_user_path(user, @user), class: "btn btn-lg btn-primary" %></li>
         
    <% end %>
 </div>
 
 
 
 
 
 
 

app/views/users/index_attendance.html.erb
<% provide(:title, "出勤社員一覧") %>
<h1>出勤社員一覧</h1>
<div>
  <table class = "table table-bordered table-condensed table-hover text-center table-striped" >
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
          <% user.attendances.each do |attendance| %>
           <% if (Date.current == attendance.worked_on) && attendance.started_at.present? && attendance.finished_at.nil? %>
            <tr>
              <td><%= user.employee_number %></td>
              <td><%= user.name %></td>
            </tr>
           <% end %>
          <% end %>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <div class="btn-users-show">
           <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
            【<%= l(@first_day, format: :middle) %>】時間管理表
           <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
        </div>
      </td>
      <td>指定勤務開始時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>指定勤務終了時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>
   
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "テスター" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード:<%= @user.id %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>   


  <% if current_user.admin? %>
   <div>
     <li><%= link_to "【所属長承認申請のお知らせ】","#" %></li>
     <div style = "margin-top:10px" ></div>
     <li>
       <%= link_to "【勤怠変更申請のお知らせ】","#" %>
     </li>
     <div style = "margin-top:10px" ></div>
     <li><%= link_to "【残業申請のお知らせ】", "#" %></li>
   </div> 
  <% end %>

  <div style = "margin-top:10px" ></div>
  
<div class ="">
      <%= link_to "勤怠を編集", attendances_edit_one_month_user_path, class: "btn btn-primary" %>
      <%= link_to "CSV出力", "#", class: "btn btn-primary" %>
      <div style = "margin-top:10px" ></div>
      <%= link_to "勤怠修正ログ(承認済)",  attendances_attendance_log_user_path, class: "btn btn-primary" %>
</div>
      <div style = "margin-top:10px" ></div>
<div>


<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
   <thead>
      <tr></tr>
        <th rowspan="3" class = "center">残業申請</th>
        <th rowspan="3" class = "center">日付</th>
        <th rowspan="3" class = "center">曜日</th>
        <th colspan="8" class = "center">実績</th>
        <th colspan="5" class = "center">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3" class = "center">出社</th>
        <th colspan="3" class = "center">退社</th>
        <th rowspan="2" class = "center">在社時間</th>
        <th rowspan="2" class = "center">備考</th>
        <th colspan="2" class = "center">終了予定時間</th>
        <th rowspan="2" class = "center">時間外時間</th>
        <th rowspan="2" class = "center">業務処理内容</th>
        <th rowspan="2" class = "center">指示者確認
          <div class = "maru size_small black">
            <div class = "letter3">印</div>
          </div>
        </th>
      </tr>
      <tr>
        <th class = "center">時</th>
        <th class = "center">分</th>
        <th class = "center">勤怠登録</th>
        <th class = "center">時</th> 
        <th class = "center">分</th>
        <th class = "center"></th>
        <th class = "center">時</th>
        <th class = "center">分</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", edit_overwork_approval_user_path(@user), remote: true, class: "btn btn-primary btn-lg" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user,day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td rowspan="3">
           <div class = "table-body">所属長承認
            <% unless @month_approver == nil %>
              <%= @month_approver.name %>から承認済
            <% else %>
        　     未
            <% end %><br><br>
          <%= select_tag 'superior', options_for_select({上長A: 1, 上長B: 2}, 1), include_blank: true %><br><br>
          <%= link_to "申請", "#", class: "btn btn-primary" %>
        </td> 
      </tr>
    </tfoot>
  </table>
</div>


<!--モーダルウインドウ表示-->
<div id="edit-overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--モーダルウインドウ表示-->
<div id="edit-overwork-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>