config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   resources :users do
    member do
      get 'index_attendance', to: 'users#index_attendance'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit_overwork_approval'
      patch 'update_overwork_approval'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' 
      get 'attendances/attendance_log'
      get 'attendances/edit_overtime_request'
      patch 'attendances/update_overtime_request'
    end
     collection {post :import} 
     member do
     end 
     resources :bases 
      resources :attendances 
    
      resources :month_approvals
   end
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
 before_action :set_user, only:[:show, :index, :new, :create, :edit, :update, :destroy]
 
  def index
    @user = User.find(params[:user_id])
    @bases = Base.all
  end
  
  def new
    @user = User.find(params[:user_id])
    @base = Base.new
  end
  
  def create
   @user = User.find(params[:user_id])
   @base = Base.new(base_params)
    if @base.save(validate: false)
      flash[:success] = "拠点登録完了しました。"
      redirect_to user_bases_path(@user)
    else
      flash[:alert] = "拠点登録に失敗しました。"
      render :new
    end
  end
  
  def show
     @base = Base.find(params[:id])
  end
  
  def edit
    @base = Base.find(params[:id])
  end
  
  def update
    @base = Base.find(params[:id])
    if @base.update_attributes(base_params)
      flash[:success] = "拠点を更新しました。"
      redirect_to user_bases_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @base = Base.find(params[:id])
    @base.destroy
    flash[:success] = "拠点情報を削除しました。"
    redirect_to user_bases_path(@user)
  end
private  
  
  def set_user
      @user = User.find(params[:user_id])
  end
  def base_params
      params.require(:base).permit(:base_id, :base_name, :base_type)
  end
  
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/views/bases/edit.html.erb
<% provide(:class_text, 'update') %>
<% provide(:button_text, '修正') %>
<h1>拠点情報修正</h1>

app/views/bases/index.html.erb
<% provide(:title, 'All Bases') %>

<h1>拠点情報一覧</h1>
<div class="col-md-10 col-md-offset-1">
  <table class = "table table-bordered table-condensed base-table">
    <thead>
     <tr>
       <td></td>
       <td></td>
       <td><b> 拠点番号 </b></td>
       <td><b> 拠点名 </b></td>
       <td><b> 勤怠種類 </b></td>
     </tr
    </thead>
    <tbody class = "table table-bordered table-condensed base-table">
     <div class = "border" >
      <% @bases.each do |base| %>
     　  <tr>
        
         <th><%= link_to "編集", edit_user_basis_path(session[:user_id], base.id), class: "btn btn-primary" %></th>
         <th>
           <%= link_to "削除", user_basis_path(session[:user_id], base.id), method: :delete, data: {confirm: "削除した宜しいですか？"}, class: "btn btn-primary" %>
         </th>
         
         <td><%= base.base_id %></td>
         <td><%= base.base_name %></td>
         <td><%= base.base_type %></td>
        </tr>
      <% end %> 
     
     </div>
    </tbody>
      
      <tr>
        <td>
          <%= link_to "拠点情報追加", new_user_basis_path(current_user), class: "btn btn-primary" %>
        </td>
      </tr>
  </table>
</div>

app/views/bases/new.html.erb
<% provide(:title, 'New base') %>

<h1>拠点登録</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @base, url: user_bases_url(@user), local: true, method: :post) do |f| %>
    <%= render'shared/error_messages', model: @base %>
    
    <%= f.label :拠点番号, class: "label-form" %>
    <%= f.text_field :base_id, class: "form-control" %>
    
    <%= f.label :拠点名, class: "label-form" %>
    <%= f.text_field :base_name, class: "form-control" %>
    
    <%= f.label :拠点種類, class: "label-form" %>
    <%= f.text_field :base_type, class: "form-control" %>
    
     <div style = "margin-top: 10px">
      <%= f.submit "新規登録", class: "btn btn-lg btn-primary btn-form" %>
     </div>
   <% end %>
  </div>
</div>