config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   resources :users do
    member do
      get 'index_attendance', to: 'users#index_attendance'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit_overwork_approval'
      patch 'update_overwork_approval'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' 
      get 'attendances/attendance_log'
      get 'attendances/edit_overtime_request'
      patch 'attendances/update_overtime_request'
    end
     collection {post :import} 
     member do
     end 
     resources :bases 
      resources :attendances 
    
      resources :month_approvals
   end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  require 'csv'
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  validate :started_at_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  def started_at_invalid
    if Date.current > worked_on
      if started_at.present? && finished_at.blank?
        errors.add(:started_at, "編集できませんでした。")
      end
    end
  end
  
 
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit_overtime_request, :update_overtime_request]
  before_action :logged_in_user, only: [:show, :update, :edit_one_month, :edit_overtime_request, :update_overtime_request]
  before_action :admin_or_correct_user, only: [:show, :update, :edit_one_month, :update_one_month, :edit_overtime_request, :update_overtime_request]
  before_action :set_one_month, only: [:edit_one_month, :update_one_month, :edit_overtime_request, :update_overtime_request]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
    def attendance_log
      @user = User.find(params[:id])
      @logs = Log.joins(:attendance).where(attendance: {user_id: params[:id]})
    end

  
  def edit_overtime_request
    @user = User.find(@attendance.user_id)
    @attendance = Attendances.find_by(params[:id])
  end
  
  def update_overtime_request
    @user = User.find(@attendance.user_id)
    @attendance = Attendance.find_by(params[:id])
    if @attendance.update_attributes(overtime_request_params)
      flash[:success] = "残業を申請しました。"
    else
      flash[:danger] = "申請をキャンセルしました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to user_url(@user)
  end

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  def edit_one_month
  end

  def update_one_month
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
    flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
    
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def edit_overwork_approval
  end
   # 一日分の残業申請
  # users/show.html.erbのhidden_fieldのパラメータ取得
  def update_overwork_approval
     # 取得できるものは以下と同じ @user = User.find(params[:id])
    @user = User.find(params[:attendance][:user_id])
    @attendance = @user.attendances.find(params[:attendance][:id])
    # binding.pry
    if params[:attendance][:overwork_end].blank? || params[:attendance][:instructor_test].blank?
      flash[:warning] = "必須箇所が空欄です。"
      redirect_to @user
    else
      @attendance.update_attributes(overtime_params)
      flash[:success] = "残業申請が完了しました。"
      redirect_to @user and return
    end
  end

  
  
    
   # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end  
    end
  private

    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    #残業情報を扱う
    def overtime_request_params
      params.require(:user).permit(:overtime_end, :next_day, :time_content, :superior_confirmation)[:attendances]
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end
  
  def format_min(time)
    format("%.2d",((time.strftime('%M').to_i/ 15).round)*15)
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
end

app/views/attendances/_attendance_log.html.erb
<h1>勤怠ログ</h1>

app/views/attendances/_edit_overtime_request.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-8 col-md-offset-1">
          <%= form_with(model: @user, url: attendances_update_overtime_request_user_path(@user, day), local: true, method: :patch) do |f| %>
        　　  <table class="table table-bordered table-condensed table-hoveres">
        　　    <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                </tr>
              </thead>
      
              <tbody>
       
                <%= fields_for :attendances do |af| %>
                   <%= af.hidden_field :id, :value => @attendance.worked_on %>
                      <tr>
                         <td><%= @day %></td>
                         <td><%= @youbi %></td>
                         <td><%= af.time_field :overtime_end, class: "form-control" %></td>
                         <td><%= af.check_box(:next_day, { :checked => false  }) %></td>
                         <td><%= af.text_field :overtime_memo, class: "form-control" %></td>
                         <td><%= af.select :superior, [["superior", "superior"],["管理者", "管理者"]],:include_blank => true ,class:"form-control" %></td>
                      </tr>
                   <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    
      <div class="modal-footer">
        <%= f.submit "残業を申請する", class: "btn btn-primary" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
    

app/views/attendances/attendance_log.js.erb
$("#attendance-log").html("<%= escape_javascript(render 'edit_overtime_request') %>");
$("#attendance-log").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集画面</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出勤時</th>
        <th>出勤分</th>
        <th>退勤時</th>
        <th>退勤分</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
       <%= f.fields_for "attendances[]", day do |attendance| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= attendance.time_select :started_at, {include_blank: true}, class: "form-control bootstrap-date" %></td>
          <td></td>
          <td><%= attendance.time_select :finished_at, {include_blank: true}, class: "form-control bootstrap-date" %></td>
          <td></td>
          <td><%= attendance.check_box :next_day_check, checked: false %></td>
          <td> 
             <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
             <% end %>
          </td>
          <td><%= attendance.text_field :note, class: "form-control" %></td>
          <td><%= attendance.select :select_superior_id, [['上長A',"上長A"], ['上長B',"上長B"]], {selected: 1}, {class: "form-contyrol"} %></td>
        </tr>
       <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="center">
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
  <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/attendances/edit_overtime_request.js.erb
$("#edit-overtime_request").html("<%= escape_javascript(render 'edit_overtime_request') %>");
$("#edit-overtime-request").modal("show");